import QRCode from 'qrcode'
import { getFirestore } from '../../database/firestore'
import { COLLECTIONS } from '@shared/constants/config'
import logger from '@shared/utils/logger'

// QR codes generated by Baileys are usually valid for 60 seconds.
// We set our internal expiry to 55 seconds to be safe.
const QR_EXPIRY_MS = 55_000

export class QRService {
  async generateQR(data: string): Promise<string> {
    try {
      const qrImage = await QRCode.toDataURL(data)
      return qrImage
    } catch (error) {
      logger.error('Failed to generate QR code:', error)
      throw error
    }
  }

  async saveQRCode(uid: string, qrData: string): Promise<void> {
    try {
      const db = getFirestore()
      const expiresAt = Date.now() + QR_EXPIRY_MS

      const qrDoc = {
        uid,
        currentQR: {
          data: qrData,
          generatedAt: Date.now(),
          expiresAt,
          scanned: false
        },
        lastScannedAt: null
      }

      await db.collection(COLLECTIONS.QR_CODES).doc(uid).set(qrDoc, { merge: true })
      logger.info(`QR code saved for user ${uid}, expires in ${QR_EXPIRY_MS/1000}s`)
    } catch (error) {
      logger.error('Failed to save QR code:', error)
      throw error
    }
  }

  async getQRCode(uid: string): Promise<string | null> {
    try {
      const db = getFirestore()
      const doc = await db.collection(COLLECTIONS.QR_CODES).doc(uid).get()

      if (!doc.exists) return null

      const qrDoc = doc.data()
      const currentQR = qrDoc?.currentQR

      if (!currentQR || currentQR.scanned) return null

      // If QR is older than 55 seconds, it's probably invalid on WA side
      if (currentQR.expiresAt < Date.now()) {
        return null
      }

      return currentQR.data
    } catch (error) {
      logger.error('Failed to retrieve QR code:', error)
      throw error
    }
  }

  async markQRAsScanned(uid: string): Promise<void> {
    try {
      const db = getFirestore()
      await db.collection(COLLECTIONS.QR_CODES).doc(uid).update({
        'currentQR.scanned': true,
        'currentQR.scannedAt': Date.now(),
        'lastScannedAt': Date.now()
      })
    } catch (error) {
      logger.error('Failed to mark QR as scanned:', error)
    }
  }
}

export default new QRService()
