import QRCode from 'qrcode'
import { getFirestore } from '../../database/firestore'
import { COLLECTIONS } from '@shared/constants/config'
import logger from '@shared/utils/logger'

// QR codes generated by Baileys are usually valid for 60 seconds.
// We set our internal expiry to 55 seconds to be safe.
const QR_EXPIRY_MS = 30_000
const FIRESTORE_OP_TIMEOUT_MS = 4000

async function withTimeout<T>(promise: Promise<T>, ms = FIRESTORE_OP_TIMEOUT_MS): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((_, reject) => setTimeout(() => reject(new Error(`Firestore timeout after ${ms}ms`)), ms)),
  ])
}

export class QRService {
  async generateQR(data: string): Promise<string> {
    try {
      const qrImage = await QRCode.toDataURL(data)
      return qrImage
    } catch (error) {
      logger.error('Failed to generate QR code:', error)
      throw error
    }
  }

  async saveQRCode(uid: string, qrData: string): Promise<void> {
    try {
      const db = getFirestore()
      if (!db) return
      const expiresAt = Date.now() + QR_EXPIRY_MS

      const qrDoc = {
        uid,
        currentQR: {
          data: qrData,
          generatedAt: Date.now(),
          expiresAt,
          scanned: false
        },
        lastScannedAt: null
      }

      const batch = db.batch()
      batch.set(db.collection(COLLECTIONS.QR_CODES).doc(uid), qrDoc, { merge: true })
      await withTimeout(batch.commit())
      logger.info(`QR code saved for user ${uid}, expires in ${QR_EXPIRY_MS/1000}s`)
    } catch (error) {
      logger.warn('Failed to save QR code:', error)
    }
  }

  async getQRCode(uid: string): Promise<string | null> {
    try {
      const db = getFirestore()
      if (!db) return null
      const doc = await withTimeout(db.collection(COLLECTIONS.QR_CODES).doc(uid).get())

      if (!doc.exists) return null

      const qrDoc = doc.data()
      const currentQR = qrDoc?.currentQR

      if (!currentQR || currentQR.scanned) return null

      // If QR is older than 55 seconds, it's probably invalid on WA side
      if (currentQR.expiresAt < Date.now()) {
        return null
      }

      return currentQR.data
    } catch (error) {
      logger.warn('Failed to retrieve QR code:', error)
      return null
    }
  }

  async markQRAsScanned(uid: string): Promise<void> {
    try {
      const db = getFirestore()
      if (!db) return
      const batch = db.batch()
      batch.update(db.collection(COLLECTIONS.QR_CODES).doc(uid), {
        'currentQR.scanned': true,
        'currentQR.scannedAt': Date.now(),
        'lastScannedAt': Date.now()
      })
      await withTimeout(batch.commit())
    } catch (error) {
      logger.warn('Failed to mark QR as scanned:', error)
    }
  }
}

export default new QRService()
